### ISSUE TITLE
Can't help contribute

### ISSUE THREAD

**Issue by JackaThompson** [pietromenna/jekyll-architect-theme#11]
Hi there,

I'm still new with using the Git command-line and App. But i tried both and each time i try and contribute to the README file, I get a 403 error with "Permission to pietromenna/jekyll-architect-theme.git denied to JackaThompson"

How can I help contribute?

**Comment by pietromenna** [comment]
Hi @JackaThompson ,

In order to contribute, you would need to send a Pull Request (generally abbreviated as PR).

I saw that you have not yet forked the repository. Having assumed that, I will try to explain to explain it here:

1. Fork the repository (More details [here](https://help.github.com/articles/fork-a-repo/))
2. Clone your fork on your computer.
3. Work and make changes on your fork, try to do it in a different branch.
4. Push your changes to your fork.
5. Send pull request (More details [here](https://help.github.com/articles/using-pull-requests/))

This works pretty much in almost all repositories in GitHub. 

I hope this helps you to reach your first contribution! I would love to help you with it.

**Comment by JackaThompson** [comment]
@pietromenna Thanks for that, I wasn't forking the repo, that's probably the problem.
